---
title: "Sejam bem vindos ao Quarto!"
---

Este curso foi planejado para aqueles que não têm nenhum ou pouco tempo de experiência com R Markdown e que querem aprender com o Quarto. O Quarto é a próxima geração de RMarkdown para publicação, incluindo dinâmicas e documentos estáticos e suporte de linguagem de programação multilíngüe. Com o Quarto você pode criar documentos, livros, apresentações, blogs ou outros recursos on-line.

## Proposta pedagógica

A intenção desta disciplina é fazer com que o aprendizado seja mais dinâmico e ocorra de forma simultânea, fazendo com que o aluno tenha as bases teóricas e teste-as ao mesmo tempo.

A proposta pedagógica para desenvolvimento deste curso fundamenta-se no conceito de `Aprendizagem Baseada em Projetos e em Problemas`. É proposto um `projeto integrador` para apreensão do conhecimento.

## Ementa da disciplina

-   Olá Quarto!\
-   Estrutura e tipos de documentos.\
-   Renderização e autoria.\
-   Cabeçalho YAML.\
-   Código.\
-   Links, figuras, tabelas de dados e formatação.\
-   Zotero e referências.\
-   Publicação de relatórios e documentos técnicos e científicos para colaboração.

## Objetivos de aprendizagem

Esta disciplina tem por objetivo formar estudantes aptos a:

-   Entender a diferença entre 'knitr', R Markdown, e Quarto\
-   Utilizar RStudio, `knitr` e Quarto para gerar documentos estáticos, websites/blogs, e apresentações\
-   Utilizar as funções e a parametrização básica para produzir documentos\
-   Criar e editar documentos como apresentações, artigos, blogs e websites

## Planejamento de encontros

Os encontros acontecerão nas **terças-feiras**, de **08:30 às 11:15h**. Serão realizados na Sala A do PPGA.

| **Data**           | **Descrição da Atividade**                                                                                                               |
|--------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| 11/10              | Instalação do Quarto CLI em diferentes sistemas operacionais. Olá Quarto -- apresentação geral de funcionalidades e tipos de documentos. |
| 18/10              | Autoria de documentos, YAML e formatos.                                                                                                  |
| 25/10              | Code chunks, Markdown, renderização.                                                                                                     |
| 01/11              | Links, figuras, layout, tabelas, notas em destaque e referência cruzada.                                                                 |
| 08/11              | Zotero, citações e lista de referências. Publicação de documentos.                                                                       |
| **Total de Horas** | 15 horas                                                                                                                                 |

## Proposta de avaliação da aprendizagem

A aprendizagem na disciplina será avaliada por meio da consolidação de atividades alinhadas com os objetivos de aprendizagem (projetos incrementais) e por meio da elaboração de um projeto transversal aos objetivos (projeto integrador).

| Pontos | Entrega                                                                                                                                              | Atividade |
|--------|------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| 15     | Lab 1 -- Introdução ao Quarto - primeiros passos                                                                                                     |           |
| 15     | Lab 2 -- Autoria de documentos, YAML e formatos - explorando diferentes possibilidades                                                               |           |
| 15     | Lab 3 -- Code chunks, Markdown, renderização. Links, figuras, layout, tabelas, notas em destaque e referência cruzada - incluindo conteúdos diversos |           |
| 15     | Lab 4 -- Zotero, citações e lista de referências. Publicação de documentos - documentos acadêmicos e técnicos e publicação de documentos.            |           |
| 40     | Projeto Integrador                                                                                                                                   |           |
| TOTAL: | 100 pontos                                                                                                                                           |           |

## Recursos necessários

Computador com Sistema Operacional à escolha do estudante para desenvolver as atividades. Os softwares a serem instalados são:

-   R (Windows) - <https://cran.r-project.org/bin/windows/base/>
-   RStudio (Windows) - <https://rstudio.com/products/rstudio/download/>
-   Quarto CLI (Windows) - <https://quarto.org/docs/get-started/>
-   Git - <https://git-scm.com/downloads>

Os alunos deverão ter uma conta gratuita na plataforma `github.com`. Recomendamos também que se cadastrem no [Quarto Pub](https://quartopub.com/)

A turma virtual do SIGAA será utilizada para postagens de conteúdos e outras comunicações.

## Bibliografia recomendada sobre Quarto

-   ALLAIRE, J., TEAGUE, C., SCHEIDEGGER, C., XIE, Y., & DERVIEUX, C. Quarto (Version 0.3) \[Computer software\]. Disponível em https://doi.org/10.5281/zenodo.5960048 (www.quarto.org). Acesso em 10 ago. 2022.\
-   HORTON, Nicholas J.; KLEINMAN, Ken. Using R and RStudio for data management, statistical analysis, and graphics. Second edition. Boca Raton: CRC Press, Taylor & Francis Group, 2015.\
-   PARADIS, Emanuel. R for Beginners. Disponível em: https://www.nceas.ucsb.edu/files/ scicomp/ Dloads/RProgramming/BestFirstRTutorial.pdf . Acesso em: 12/11/2019.\
-   TEETOR, Paul. R cookbook: Proven recipes for data analysis, statistics, and graphics. Sebastopol: O'Reilly Media, Inc., 2011.\
-   [Quarto](https://quarto.org/)
-   [rstudio::conf 2022 Workshop - Getting started with Quarto](https://rstudio-conf-2022.github.io/get-started-quarto/) e [Github](https://github.com/jthomasmock/quarto-workshop)

## Comunicação

Toda comunicação individual com a docente deverá acontecer por meio do email institucional do docente, deve conter no campo "assunto" o texto `<quarto-PPGA>` e deve ser assinada com seu nome completo. Por favor, utilize o email institucional para comunicação com o docente: [renataoliveira\@cefetmg.br](mailto:renataoliveira@cefetmg.br)

## Políticas institucionais e da disciplina

Os estudantes e professores têm a responsabilidade de manter um ambiente de aprendizagem adequado e motivante. Aqueles que não aderirem a tais padrões de comportamento podem estar sujeitos ao regime disciplinar da instituição. A cortesia profissional e a sensibilidade são especialmente importantes no que diz respeito a indivíduos e discussões que lidam com diferenças de raça, cor, cultura, religião, credo, política, status de veterano, orientação sexual, gênero, identidade e expressão de gênero, idade, deficiência e nacionalidades. As listas de classes são fornecidas ao instrutor com o nome legal do aluno. Terei prazer em honrar seu pedido de dirigir-se a você por um nome alternativo ou pronome de gênero. Por favor, me informe essa preferência no início do semestre para que eu possa fazer as mudanças apropriadas em seus registros.

Não serão tolerados atos de discriminação ou assédio contra ou por qualquer funcionário ou estudante.

Honestidade acadêmica é um princípio fundamental desta disciplina. Desonestidade acadêmica configura-se por: cópias literais de textos ou ideias sem citação de fonte, fabricações e falsificações de qualquer natureza, plágio, mentira, suborno, comportamento ameaçador ou cumplicidade com desonestidade acadêmica em qualquer nível. Os estudantes que forem considerados em violação da política de integridade acadêmica estarão sujeitos tanto a sanções acadêmicas do membro docente quanto a sanções não acadêmicas. Se você tiver alguma dúvida sobre citações adequadas, configuração de plágio, etc., por favor, não hesite em perguntar!
